language: node_js
before_script:
 - npm i
 - npm run build
node_js:
  - "6"
  - "node"
sudo: required
services:
  - rabbitmq
env:
  - RABBITMQ_USER=guest RABBITMQ_PASSWORD=guest RABBITMQ_HOST=localhost