language: node_js
before_script:
 - npm run build
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
sudo: false
dist: trusty
services:
  - rabbitmq
env:
  - RABBITMQ_USER=guest RABBITMQ_PASSWORD=guest RABBITMQ_HOST=localhost
