language: node_js
before_script:
 - npm i
 - npm run build
node_js:
  - "6"
  - "8"
  - "9"
sudo: false
dist: trusty
services:
  - rabbitmq
env:
  - RABBITMQ_USER=guest RABBITMQ_PASSWORD=guest RABBITMQ_HOST=localhost
