language: node_js
before_script:
 - npm run build
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
sudo: false
dist: trusty
services:
  - rabbitmq
env:
  - RABBITMQ_USER=guest RABBITMQ_PASSWORD=guest RABBITMQ_HOST=localhost
script:
  - npm test
  - npm run doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs
  on:
    branch: master
